version: '3.8'

services:
  little-endian-test:
    build:
      context: ..
      dockerfile: docker/little-endian/Dockerfile
    platform: linux/amd64
    volumes:
      - ../build-le:/workspace/build
      - ../coverage-le:/workspace/coverage
    environment:
      - ENDIAN_TYPE=little

  big-endian-test:
    build:
      context: ..
      dockerfile: docker/big-endian/Dockerfile
    platform: linux/s390x
    volumes:
      - ../build-be:/workspace/build
      - ../coverage-be:/workspace/coverage
    environment:
      - ENDIAN_TYPE=big