name: CI Checks
on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build and Run Tests
        run: |
          sudo apt-get install -y lcov sed ruby
          cmake -S test/unit-test -B build/ -G "Unix Makefiles" -DBUILD_CLONE_SUBMODULES=ON -DCMAKE_C_FLAGS='--coverage -Wall -Wextra -Werror -DNDEBUG'
          make -C build all
          cd build && ctest --output-on-failure
      - name: Generate Coverage Report
        run: |
          make -C build coverage
      - name: Check Coverage
        uses: FreeRTOS/CI-CD-Github-Actions/coverage-cop@main
        with:
          coverage-file: ./build/coverage.info
          branch-coverage-min: 100
          functions-coverage-min: 100
          line-coverage-min: 100

  endianness-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov
      - name: Run Little Endian Tests
        run: |
          docker build -f docker/little-endian/Dockerfile -t dcep-test-le .
          docker run --rm -v "$(pwd)/build-le:/workspace/build" dcep-test-le
      - name: Run Big Endian Tests
        run: |
          docker build -f docker/big-endian/Dockerfile -t dcep-test-be --platform linux/s390x .
          docker run --rm --platform linux/s390x -v "$(pwd)/build-be:/workspace/build" dcep-test-be
      - name: Combine Coverage Reports
        run: |
          mkdir -p coverage-combined
          lcov --add-tracefile build-le/coverage.info \
               --add-tracefile build-be/coverage.info \
               --output-file coverage-combined/combined_coverage.info \
               --rc branch_coverage=1
          genhtml coverage-combined/combined_coverage.info \
                  --output-directory coverage-combined \
                  --rc branch_coverage=1
      - name: Check Combined Coverage
        uses: FreeRTOS/CI-CD-Github-Actions/coverage-cop@main
        with:
          coverage-file: ./coverage-combined/combined_coverage.info
          branch-coverage-min: 100
          functions-coverage-min: 100
          line-coverage-min: 100
      - name: Upload Combined Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: combined-coverage-report
          path: coverage-combined/

