name: CI Checks
on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build and Run Tests
        run: |
          sudo apt-get install -y lcov sed ruby
          cmake -S test/unit-test -B build/ -G "Unix Makefiles" -DBUILD_CLONE_SUBMODULES=ON -DCMAKE_C_FLAGS='--coverage -Wall -Wextra -Werror -DNDEBUG'
          make -C build all
          cd build && ctest --output-on-failure
      - name: Generate Coverage Report
        run: |
          make -C build coverage
      - name: Check Coverage
        uses: FreeRTOS/CI-CD-Github-Actions/coverage-cop@main
        with:
          coverage-file: ./build/coverage.info
          branch-coverage-min: 100
          functions-coverage-min: 100
          line-coverage-min: 100

  endianness-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run Little Endian Tests (x86_64)
        run: |
          echo "Building Little Endian Test Container (x86_64)..."
          docker build -f docker/little-endian/Dockerfile -t dcep-test-le .
          echo "Running Little Endian Tests..."
          if docker run --rm dcep-test-le; then
            echo "LITTLE ENDIAN TESTS PASSED"
          else
            echo "LITTLE ENDIAN TESTS FAILED"
            exit 1
          fi
      - name: Run Big Endian Tests (s390x)
        run: |
          echo "Building Big Endian Test Container (s390x)..."
          docker build -f docker/big-endian/Dockerfile -t dcep-test-be --platform linux/s390x .
          echo "Running Big Endian Tests..."
          if docker run --rm --platform linux/s390x dcep-test-be; then
            echo "BIG ENDIAN TESTS PASSED"
          else
            echo "BIG ENDIAN TESTS FAILED"
            exit 1
          fi
      - name: Endianness Test Summary
        if: always()
        run: |
          echo "ENDIANNESS TEST SUMMARY:"
          echo "  - Little Endian (x86_64): Tests completed"
          echo "  - Big Endian (s390x): Tests completed"
          echo "  - All endianness tests verify network byte order handling"

